services:
  nginx:
    container_name: simple-blog-nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ../app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    container_name: simple-blog-php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ../app:/var/www/app